// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOiQg6Ztiyxgrfeh6QbqS9_Ot658tqlgI',
    appId: '1:329799362596:web:d6280c3b583e3ad90150b1',
    messagingSenderId: '329799362596',
    projectId: 'studentapp-eef05',
    authDomain: 'studentapp-eef05.firebaseapp.com',
    storageBucket: 'studentapp-eef05.firebasestorage.app',
    measurementId: 'G-8859CZBRF9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2pL1uTnjOu5YqelOk0RXlxPPxN7g977U',
    appId: '1:329799362596:android:fdb87388be44da3f0150b1',
    messagingSenderId: '329799362596',
    projectId: 'studentapp-eef05',
    storageBucket: 'studentapp-eef05.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEk6O2UOlE3CaBR77Sbj4IBKV4d38gECE',
    appId: '1:329799362596:ios:6f0cafed8bf2a48b0150b1',
    messagingSenderId: '329799362596',
    projectId: 'studentapp-eef05',
    storageBucket: 'studentapp-eef05.firebasestorage.app',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBEk6O2UOlE3CaBR77Sbj4IBKV4d38gECE',
    appId: '1:329799362596:ios:6f0cafed8bf2a48b0150b1',
    messagingSenderId: '329799362596',
    projectId: 'studentapp-eef05',
    storageBucket: 'studentapp-eef05.firebasestorage.app',
    iosBundleId: 'com.example.studentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAOiQg6Ztiyxgrfeh6QbqS9_Ot658tqlgI',
    appId: '1:329799362596:web:99facd5fc077898f0150b1',
    messagingSenderId: '329799362596',
    projectId: 'studentapp-eef05',
    authDomain: 'studentapp-eef05.firebaseapp.com',
    storageBucket: 'studentapp-eef05.firebasestorage.app',
    measurementId: 'G-NQ3K8RX738',
  );
}
